---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:coqHlVSm09GP9vcLzw7gxke7pfIyE4qxPjutoMeRekC9YfGpdkugLfmGzieKPFXQ/Q7ZMdw=,iv:6LTGyzeipHmBXDyauz2sRu3xH4VzZsB8rWCvdQ/p/pE=,tag:0jg94bOGA0tdA1WJqJYRDQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCc3UydFVNSGQxaUtvQXFF
        bkxWdXlMNWdnbWRhZ2IwOTY5eC85TmluUWo4CllkRlgwUENUald6SGxseEgwdCsx
        U0xpYjdSb2dyWktkQXZjMnRpTDhXZ0UKLS0tIGdob053ZEhjNmREWHFSQjBiQ0Fp
        RE83OWcxRlM0c2MxZ3ZuS3VicWNOOFEK0HeWBnMDUWzXAdaCgnuT/5TXJdsRNwnE
        wjN8jGagSHRVazSY1ItVoys08n6D2LlKUv14u5hC8Fs1Jg+0eF9hsw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1djuea8j8v5wysv7urq7qenceycxx5xayck0mate39ekz2mj8sf7q8us7wl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-24T17:11:09Z"
  mac: ENC[AES256_GCM,data:Dvu7bfBOkN7I4Q/EaGZhsDkVO5FOPsZUVGSq6a4pLdSiI+saCA2GIX8NS/WxYfzIcoCtwfz2NS1uYAsVRjvCfTydr3cfhmNho7RCWaa4XNa9KHxndkqz/tK7YlKgTHhpaVzVAgkuIcgNgBJcWyQ5TDIqY5cudiisY8qY0wkjunY=,iv:EHl7D5p0rj2PT9sVv37RCkjXbZHyvxrOJoMhoAUiYVY=,tag:yJkOjnLUE4JZhyjWMd8J1g==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
