---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Bs/O6/XdJ9aykKH85/Ds20qDLVuXIwZ2183HePGRY3GN8Ke/vPkokO7a0/9tLZyctr1fcmw=,iv:zWICh5WPwepmqFMdgK5Q8+p+taV1OGhuigQF8MDTNkA=,tag:CSMMvFA5tq3fdcaiLOk0Qw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSkF0akQyRnhSQ3ZkZzR5
        UExxdFplWG1rekYrZ2JXU3hLVXhoTEFoYVVFCng3NTIzSGJZcUlMNm1BSlF3d0Uz
        NjF4eWROdE1RQ2plTmlOckxZZlNLb00KLS0tIG5yWWxYdGpDREZMOWVzb3QzTk5M
        Qm5iYi9WUWVoSW05Vm81aGlBT0NKUTQKjZG/ORFG3TbfqHsLqtQc75+Jd5xSjGfA
        mz7u8OsqcCFjyKzREDk5BLpkqj1Itv/VAPAYp1GlZpmiySBLoxztUQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1djuea8j8v5wysv7urq7qenceycxx5xayck0mate39ekz2mj8sf7q8us7wl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-24T14:21:16Z"
  mac: ENC[AES256_GCM,data:n9CJ209yn7qcH68M84zf33QZjf9j2EBGot070B1RqJRSH3Ho/dyORKvzwFcTE9F3GqYEFjYNy36ENo0BJI7QrcuQWR5pmFzJJMTcLmG3wY/tix0ZqgyG0rTQzFKaayyr0YBdXS8TzSE6c5pJ/J+3wENMunYu26zpwhFOFjCLMtA=,iv:3fWK06+2vVb/yNUQlVmXKBjO5f+PJ7BDM3ruNeivR9I=,tag:f05+Q19oLxnJ5Ma7QGKMnA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
