---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:J/TvoJIX+2go4g==,iv:okzMj3k/vfnUkv9U/6NvANoV5g0y3V5V7cep45OlqGo=,tag:fsW1o+dPGfhLCGIMvRkjSg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMlIveVJKN1hlMHNIYktw
        RnpyTzZOTU41QzczZGJtMkpiOGFRRmdFL0hvCklsa3N0WEZDd0tUak1KU3ZzWTZr
        NFdhNHpqdEozSE8rejNQZDZ4aFFSM3MKLS0tIGo0S2dqbm5KWFFDZUgweEdKeXlT
        MHV3SitqbVBuLzJZM3IyenU0RHJMV0kKL7j6W/bRWr9JMNmfnP4ifnkrkHg4AyGb
        EyCFFoYtjGzL05h0eKZHxDlr9fSYud9Ettq0vKnRBYO0YXMkQaDpdw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1djuea8j8v5wysv7urq7qenceycxx5xayck0mate39ekz2mj8sf7q8us7wl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-24T17:11:09Z"
  mac: ENC[AES256_GCM,data:JAN1cXx9coqLs/fn8UbhWRIBWNAra2ufBO8+3hxDFvqyu7zrU/b3SCgpEdQOIkOGBLdvBU82nfQefWIfKHBnIXdwXvcoLV2iUeUevSBO3D5KvLUoJJ5CA3V8n7fDT2HW9UGUn/FG7b+LZ5KnVIChWLvzMeBdoDQZ+8IIsvrwz1I=,iv:3KSrLuCssntDy29S9+kG0RRfnI8Owts7ceNoMshVwN0=,tag:jpN/p2NWRM0MYzwu/ehVPg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
