---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:d4/HE9+xTcp50Q==,iv:7MtWumrS32riRarUF7vCNupdbA07kR0Rx/V+FD58Hqk=,tag:G1vKzxodQoqbHRWB9MrgnA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQ1pnYWhCOHlGUGxEa1Ur
        bXRPQmRaRjM0OTIrNmRVWnBsdk82TDdvR2pFCjVQd0ltUkJpRnFyNWZoVXpZVmNV
        OFh6ZjY1ZGZVK05YejNiUWlSOU5UTjgKLS0tIGhCdGFoVkFFNVBrOG0xTkdFdlc4
        bkdzcThvVnlFZ1ZMSWpXOWRMRmxxczgKCs/RJdF8E/vmcJ1n9fvvtOjw6W0jPw6c
        kD2dgoYfYvupOl6EMmuISq/gpRWHynu9omP2jm3F3ffz+zyC3Y7RGQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1djuea8j8v5wysv7urq7qenceycxx5xayck0mate39ekz2mj8sf7q8us7wl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-24T14:21:16Z"
  mac: ENC[AES256_GCM,data:Gd0bsZQkkTQ5J72i7vn6SQVq1bziKmvXU/m9U7xJRhJU/IXq/33i88Y7xSOi4HyxoXHT6ANYD9KqGPdvM5cnv7g15eo0a1Th8zAi6XGHgn2UEVdPVlgK4TZZmwDy7Bg4BgsWJjXSI7JvBaNFU09GqDdw7cm0ydzMl9VKNJ8r3Hk=,iv:wVOY5LpntaaaM6I0Y/R4/YQZ+Uh1ZU+DXqLFCQZS5FI=,tag:cD+D1OYfc1Z8URvywVZYiA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
