---
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Q2XMLiXcic+n6GjkKrK2t+6LOfWKynWkmsfW2G9D+a0=,iv:EcmTxD6mMNwwx5tNA17uNutC5m+s9MNFcilLULQBT9w=,tag:1Eh1V292Mds7JZc3lCPlLQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKOVo1Z1J3alVBc3RuRFVj
        WVdXNW4yMWZ5Zk1LUDBoZm9BTldBdFdjNENZCnpwUmdJS3NrTDQ2alhYdndyN0lU
        ck5adzJDdDkzcng5RWJBeE9HRktKZFUKLS0tIFZYTE9HbWV0clUzK2QvS2pVVllp
        SU1UY3hVdDF2a2w2WWdIQ2QyVEprTjAKIAlMJbgb8UcECZnT0Ss7BZEarQIVje1x
        AcQW8UjEF8J8DzFO4aTqa0mCexnAS5ZsLi0LAA0ddkSxICKgEB9H2Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1djuea8j8v5wysv7urq7qenceycxx5xayck0mate39ekz2mj8sf7q8us7wl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-24T17:11:09Z"
  mac: ENC[AES256_GCM,data:0wtzQ4/t5r3+yMdJw8nt+vqbI7qgKlqCFaLPE73GQxL6MMK+GmuP83Bgvzplh2kobqWxLBi3CT602NjfiJXUwNRR9S2w58hzUgOlpf9QxKuC2T76ndVATd8Y9agqs2VEK/B+qgexT1jAYmMrcO/OhtcyLoGeR/UOJqJyr6yIitw=,iv:WYjneEWCo/wCDQV6FqJ32TmBLyhlKKl2XoXWU+37hHA=,tag:HZi5HUvXPkJ7tviuLsPZ0A==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
