---
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:+0Dug4SAEEXizbxaEUbBVS5N0w0Lv+t7mr/c1LFuE48=,iv:mG2e2pRA02Fy0yti+VqQJKiQtdTEtD7R99gy2SBf59k=,tag:HTIuzcQEVT03ZpcWET6pbw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMXRKQzM1VHdTOHp0TlFD
        ZzNFVFJnUFN6cENEK21ld09tNzhIclg2L2tjCkN2Y0k5cXdpaEMxYVRKOVdPdFV4
        L0x4RzlMOFRVcEVlbWtqenBJUk9uWTAKLS0tIHRlaUFPK3hEWE5sTEVtR3ZIMDZN
        cm94M3JxWDNrdThWM21BZXhobk4zcEkK+hkFM5y7bn9hSCAkY0I8Vmx9ldYTEJAP
        y/LqCf7rnLJzBSf7vbKcwIk4Susn6zyyQR3pj5I7xeGRxwPGOmCiqw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1djuea8j8v5wysv7urq7qenceycxx5xayck0mate39ekz2mj8sf7q8us7wl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-24T14:21:16Z"
  mac: ENC[AES256_GCM,data:zsS7LyEOGF3ugO5sC53typDI2UtJs3Dz19/QQgVDNZiU1a201DmybGFV3RJgNQQFf3zbBkGcd5bLfWGYfDzlH7lCXBuXcfOVHl7Tv9r9q1BGYksSELrlIhezNsfN5DTU8ywkpKvP/C1dx3fGx67DdjFCtmQ+PfBps6f6czZ0VDI=,iv:9Xtl4+t93CQ1KDLzo6YkcgHCTPb8D9fBisNua8cJpvI=,tag:Sp+vcHbFT3ImPLza2Okarg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
