---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:eUff1guDUxpM/IxjVdplGiuphb/dyV4tFgVJZhskLvkJNUuVZNxfv/xdokDdBXC6e5+6KTBLuEXuo1b2Wb1pHi8ohwITjK8CyJzNC293cOFEZwPa+2J7eYz7Dgy8vHQwriaxF0YM8CuaMkqiuCA624W7y+7gxttEjtxx1hTyxsz7bnFtNrLerXNZxvVsu+fwJgFFOeDw/Dftq1IIkJPHSoXXX9Fw9vtVdGjJ7LJyVPIbyrLB,iv:603tbyFz9NKP1LcDe1x9dyyWkdAKNTgaizbrkpPMnhM=,tag:AV2Ktvro0xtDP9ok4a+6kw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6N3FKc3JqRmZJS3EyeTc1
        TitLeE5sUEhmWSs5N0hFYnhzTUJUbnI3WG4wCkF1NEJPQ2lQRlNOajNZY3pFeXl3
        UHVZYjQxeENXNXJCOXVYODJHMmFoZlEKLS0tIHRYWno5dUZYTGxRUllWdkgyb2du
        ODdRQnI2MXNWT1I2NDRxSFZEMFYySm8K1XD2gLZ/ErtSg59ZRowsoAkW8NhAjuDo
        Wxvwg0e+YMGxrNPygCDMIxYh+dzQvyK/09B9d+DTUdxJ9N2mj97VCQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1djuea8j8v5wysv7urq7qenceycxx5xayck0mate39ekz2mj8sf7q8us7wl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-24T14:21:16Z"
  mac: ENC[AES256_GCM,data:TzA9WU/iJgG3EOCDz95Eh96hG/EBCAxbYJw9ZoG2hUn4DHyhLC1YGs8g0nyBnmB1yNiiYtDGsTkfHTkgVqoymkh3GELBjUo+H3rBrHmtRu3Bvf4IjtH6XQtpp0/nijx44mMSJrcROhtV5gudSj2F/HH0MEnoJqaRUk+wH2fBFiQ=,iv:5OF2cQqf5QuQ8W02yWJbickDV+r1M6eXH8CprvWKK6Y=,tag:h52qtsraVHhv8UvbDe/RAQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
