---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:n9YsDPtGS9vsxiOIBSrX7SE69QlNz29UuE4n6JuFNs8CSKeByQRn0ZLsogOfEk/n7/Joz15L0vYr5vAxAOgU93fYKyo0x6Vs6aGnr04kYn7zwX+Z2bPUhD1z8CY3VMvOTF6nnE2Bl+KBccd/KX3WBLUJQk1Xuc1ouz+xZG+1NhrY+Q96UVH4vdZg4aMQ2UZ1oqhKRHDV3eW8HJu1dgOsp/NuiaSl0NRyC2ht5pb9vy4NMXSr,iv:hSa98fiDBqAFvvMITHVvCbgOD0gUbw90ZzhgxOj2A+Y=,tag:9xRWpudqrwmIk8GQIH0Vlw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWFF5VVNEb2E0emJXZVJy
        aW5yQk1TTldLb1hoek5kN25OVVZvZytDUlNFCjdRZkdYcnZubVNhdHVVbDNZMjJs
        cHZuTUNwNFBleUhkTjRwNVFOcWVNUGsKLS0tIGxkNzBMUEFwWXJUMUgydG55VkNV
        ZHVCWDA3YjM1V1JHT3JlbDd2MC9zZ28KJBy0GjZ1mIHCFvOVvQmQwoMl0ue3kQND
        w7A/SeAvEDfWeVYAOaGZkg5fmcntsv72u5/+h+BiB4FdUDhYBYCN4w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1djuea8j8v5wysv7urq7qenceycxx5xayck0mate39ekz2mj8sf7q8us7wl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-24T17:11:09Z"
  mac: ENC[AES256_GCM,data:7eWqUKmYPga1iH5YO9np/s4Fm0mUhs0wBBjMjFAPM++oy8Kcw4hxWtXxzTzIsXbvfwMXCWQXxhz56KS0eR8WCBQKD12nG3RLSg2aZpiwWq8hcAknyrPgM4mga8qrQ5Cv+yY71AqcEmI1FPVVlVjTRcFctVV4C1AueXq7w4qKtgs=,iv:2fVkO7voJ9N4N5QuMqtEUINyocksLNsaUUuxvS+i81w=,tag:zU3hAg0BfD058GMrE/9L8w==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
