---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Np+8vInNoYnFfNZJuM2hwoNjBxyWbaEV45Xe6FrYA1ONq3w0BcmD0BTSUrUgPgydmiivoQI=,iv:ruqSHJkfCeXZAwzjIefhiDatgWkPeqT9PmwUuI3GFes=,tag:czE1TBYzPEoxzd+7S+Li8A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZjdhYS8zUHVVdGFxaHdv
        R3ZiWkhPTVh2QXNSZ1krcUt1b0hUbzBzREZJCkt3elFQOWxDZHB2NitXMkVaejMr
        WTYvWmV0K0N0dVpRS0xNcHYzWEtXazQKLS0tIHV0SWVSNGNSRXNvRlV1Qm0zRGpp
        L29XMVpwbzNhOUZiZjlLdkcvR1FoUUUKf0A8T0vp+V7CuK47x3ghm73yYAF3rI0l
        D9s2MX1RLthgRs2jt5pGIqV11f1k1axyMe4DD+DZZXKnCFKjm6DNxA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1djuea8j8v5wysv7urq7qenceycxx5xayck0mate39ekz2mj8sf7q8us7wl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-24T17:11:09Z"
  mac: ENC[AES256_GCM,data:IkjiUgD6Jdnhi5GE67YYQlE1X7SGe2GIyDyZ19pLKkpUQHbQQDAEgUfTvpVwA9PFqSO5Z/M2Nrn4JdHkww37St5xjq/mwgMA2P2jfb7x1D7R113B0MsmK3OnHWhXe8I4ozRK4dWTJd2inA/zhW6OJVQSd8FmmhFp2Bdp4HEY1/o=,iv:hFVCuQOXJ+yS9VMce3o/7EmfaicoU2yWNzq0u2XP/8A=,tag:SqhqSvXNYzM7P7hHwL83nQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
