---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:nPVE8abMNFt48uJBVAjVtMHYTEW5WNaqR+V5GqywKdc/CvyEwKTEj0Xx+TGSjAsjd3W6ciY=,iv:qGlYQtsLdSX5INTEoQ7/iWYgDigpEg8j63xDtR2UQTE=,tag:pAi0mrbCeTNzAO6yTVJ5Lg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbnBPMnMwYzlpekowaGVx
        V050UzVrVEFDc3VDSm5BdURHSUlDb0dMR2tNCm1Gdk80UXBhWWVJeUhLbDc1NEZ6
        ei9DK1c2NExIV1JYb004NithNjdpQ1kKLS0tIE4zZ1AyVWt3ZjZyVDV1N2FXbVFM
        Y1p0NW5iUlBMbGJKa1lNc0dvclBwMFkK2J1i4QfPUC2e6/wS7gUj5jS0i0IfW5VW
        hqLXGGc84KJ+61DK2FBQQz6cL+Fr4F+7CGbCNSvtv4WWQ9TwGBXeIw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1djuea8j8v5wysv7urq7qenceycxx5xayck0mate39ekz2mj8sf7q8us7wl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-24T14:21:16Z"
  mac: ENC[AES256_GCM,data:gnQxu6wN9XhldB443fUAg50Gdv1NlNBYOkMHG2ymc+vwyF+/eehy/HmkklKzUM3ZAeM218lViWWiglL2XtDiiXQyWczk2f6jtlb6czJZRQ0yo6qxowMf5pyxTL+ROzvQYjk7PIcH/2tXqVbPcwlkIyVzFioqgZ4UkF8Zefwrt7Q=,iv:oQiGleDgBUkAY9fEFLMDolI9fKr26mKzGOh1tHAlY2E=,tag:tzJxBmZcTexcFo5DWKJUeg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
